#!/usr/bin/env bash
set -e

# build
cp -R ./src/demo-app/ ./target/demo-app
cp -R ./src/platform/ ./target/platform
cp package.json ./target/package.json
cp ./src/demo-app/index.html ./target/index.html
cp ./test/karma.conf.js ./target/karma.conf.js
cp ./test/karma-test-shim.js ./target/karma-test-shim.js
cp Gruntfile.js ./target/Gruntfile.js
cp ./src/demo-app/gh-pages.* ./target/
cd ./target
npm install
npm run build:demo-app
npm run build:platform
